/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alertasinventarios;

import alertasinventarios.Bussiness.Consumos;
import alertasinventarios.Bussiness.InventarioActual;
import alertasinventarios.Bussiness.OrdenesDeCompra;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.BorderLayout;

/**
 *
 * @author ASUS
 */
public class InterfazMenu extends javax.swing.JFrame {

    /**
     * Creates new form InterfazMenu
     */
    public InterfazMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo de SKU");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Calcular disponibilidad de SKU");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jToggleButton1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked

        String SKU = jTextField1.getText();

        Consumos Consumos = new Consumos(SKU);
        InventarioActual InventarioActual = new InventarioActual(SKU);
        OrdenesDeCompra OrdenesDeCompra = new OrdenesDeCompra(SKU);
        double PromedioConsumoSku = 0;
        try {
            PromedioConsumoSku = Consumos.promedioMensual();
        } catch (IOException ex) {
            Logger.getLogger(InterfazMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        double InventarioActualSku = 0;
        try {
            InventarioActualSku = InventarioActual.Suma();
        } catch (IOException ex) {
            Logger.getLogger(InterfazMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        double TotalInventarioEnComprasSku = 0;
        try {
            TotalInventarioEnComprasSku = OrdenesDeCompra.Suma();
        } catch (IOException ex) {
            Logger.getLogger(InterfazMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

        double SaldoInventarioSku = InventarioActualSku - PromedioConsumoSku + TotalInventarioEnComprasSku;
        if (InventarioActual.isSkuEstáEnBaseDeDatos()) {
            try {
                System.out.println("El inventario actual para el Sku " + SKU + " es de: "+InventarioActual.Suma());
                System.out.println("El consumo proyectado para el próximo mes para el Sku " + SKU + " es de: "+Consumos.promedioMensual());
                System.out.println("las entradas por compras en el próximo mes para el Sku " + SKU + " es de: "+OrdenesDeCompra.Suma());
                if (SaldoInventarioSku <= 0) {
                    System.out.println("Se prevé que el Sku " + SKU + " se va a agotar durante el próximo més");
                } else {
                    System.out.println("Se prevé que el Sku " + SKU + " tiene suficiente inventario para el próximo mes");
                }
            } catch (IOException ex) {
                Logger.getLogger(InterfazMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("El SKU que escribió no existe por favor intente con otro SKU " );
        }
        InterfazMenu InterfazMenu = new InterfazMenu();

        InterfazMenu.hide();
    }//GEN-LAST:event_jToggleButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
